object Versions {
    const val Kotlin = "1.6.20"
    const val Coroutines = "1.5.0"
    const val BuildToolsVersion = "31.0.0"
    const val AndroidGradlePlugin = "7.1.2"
    const val Material = "1.5.0"
    const val AppCompat = "1.4.0"
    const val Compose = "1.1.1"
    const val CoroutinesAndroid = "1.5.0"
    const val AndroidXCore = "1.7.0"
    const val Timber = "4.7.1"
    const val ActivityCompose = "1.3.0"
    const val Arrow = "1.0.1"
    const val Navigation = "2.4.2"
    const val SerializationJson = "1.3.1"
    const val ComposeCompilerVersion = "1.1.0-rc02"
    const val ActivityComposeVersion = "1.4.0"
    const val CoreSplashScreen = "1.0.0-alpha02"
    const val DetektVersion = "1.18.1"
    const val KtlintVersion = "10.1.0"
    const val CoreLibraryDesugaring = "1.1.5"
    const val Accompanist = "0.21.5-rc"
    const val DrawablePainter = "0.15.0"
    const val Retrofit = "2.9.0"
    const val OkHttp = "4.9.3"
    const val GoogleServices = "4.3.10"
    const val Crashlytics = "2.8.1"

    const val AndroidJUnit4 = "1.1.3"
    const val Espresso = "3.4.0"
    const val JUnit4 = "4.13"
}
