# Workflow name
name: Build Staging application
on:
  # When it will be triggered
  # And in which branch
  pull_request:
  push:
    branches:
      - test_actions

# Where will they run
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 1.8

      ## Build all our Build Types at once ##
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease
      - name: Run Kotlin Linter
        run: ./gradlew ktlintDevDebugCheck

